export const environment = {
  production: true,
  name: 'prod',
  region: 'eu-west-1',
  recaptchaV3SiteKey: "6LdTLQsfAAAAANYSrgd4Tb9a1_K8svxdC-KuFJFL",
  binanceEndpoint: 'https://api.binance.com',
  beUrl: 'https://api.anton.finance/v1',
  cognitoAppClientId: '1a2dtr401gg6i0gdsaerr96r7m',
  cognitoUrl: 'https://auth.anton.finance',
  cognitoUserPoolId: 'eu-west-1_CjFRWAFy6',
  accountId: '682060008544',
  identityPoolId: 'eu-west-1:7321d2ea-1614-46cb-9da5-ada33db4960f',
  userTable: 'registry',
  transactionsTable: 'transactions',
};
