version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: node:14
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Installing dependencies
          command: npm install && npm install --prefix ./ci
      - run:
          name: Building project
          command: npm run ci:${CIRCLE_BRANCH} && mv src/assets dist/anton-webapp/assets
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3 and Invalidating Distribution
          command: yarn deploy:${CIRCLE_BRANCH}

workflows:
  version: 2
  build:
    jobs:
      - build_project:
          context: aws-context
      - deploy_project:
          requires:
            - build_project
          context: aws-context
